#33 update downloader image with classifier usage
i-Cell-Mobilsoft-Open-Source/docker-base pull request #34
Opened 2023-11-20 11:02 UTC by cserhatit

2023-11-20 11:04 UTC, rombow approved these changes

2023-11-20 11:29 UTC, speter555 approved these changes

2023-11-20 12:44 UTC, vasizs approved these changes

2023-11-20 14:45 UTC, vasizs submitted a review, later dismissed

2023-11-21 08:40 UTC, rombow requested changes

2023-11-21 08:40 UTC, rombow commented on script/artifact/sonatype-download.sh
> +NEXUS_DOWNLOAD_OUTPUT_FILE_NAME=${NEXUS_DOWNLOAD_OUTPUT_FILE_NAME:-"$NEXUS_OBJECT_ARTIFACT_ID-$NEXUS_OBJECT_VERSION-$NEXUS_OBJECT_CLASSIFIER.$NEXUS_OBJECT_EXTENSION"}
Ez oda vezethet ha nincs classifier hogy "-" benne marad alapbol:
"artifactId-version-.ext"

2023-11-21 08:40 UTC, rombow commented on script/artifact/sonatype-download.sh
> +SONATYPE_API="service/local/artifact/maven/content?r=central-proxy&g=$NEXUS_OBJECT_GROUP_ID&a=$NEXUS_OBJECT_ARTIFACT_ID&e=$NEXUS_OBJECT_EXTENSION&c=$NEXUS_OBJECT_CLASSIFIER&v=$NEXUS_OBJECT_VERSION";
&c=$NEXUS_OBJECT_CLASSIFIER
ures ertekre jo artifactokat fog talalni?

2023-11-21 08:50 UTC, rombow approved these changes

2023-11-21 20:43 UTC, speter555 approved these changes

2023-11-21 20:46 UTC, merged